version: '1.0.0'
name: enkindb-review
services:
  ekinsadb-review:
    container_name: ekinsadb-review-v0.2.0
    hostname: ekinsadb-review
    build:
      context: ekinsadb-review
      dockerfile: Dockerfile
    image: ekinsadb-review:latest
    ports:
      - "8091:8091"
    networks:
      - public-network

  ekinsadb-review-front:
    container_name: ekinsadb-review-front-v1.0
    hostname: ekinsadb-review-front
    build:
      context: ekinsadb-review-front
      dockerfile: Dockerfile
    image: ekinsadb-review-front:latest
    ports:
      - "80:80"
    networks:
      - public-network

networks:
  public-network:
